name: fact_about_cat
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  retrofit: '>=3.0.0 <4.0.0'
  logger: any
  dio: ^4.0.6
  json_annotation: any
  provider: ^6.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: any
  build_runner: any 
  json_serializable: any
  hive_generator: ^1.1.3



flutter:
  uses-material-design: true
  assets:
   - assets/cat.png
